version: "3.8"
services:
  app:
    build: .
    container_name: alfasoft_app_prod
    volumes:
      - .:/var/www/html:ro
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: recruitment.alfasoft.pt
      DB_PORT: 3306
      DB_DATABASE: matheusestrela-lv
      DB_USERNAME: matheusestrela-lv
      DB_PASSWORD: KrJoVOjWykgaYUH

  web:
    image: nginx:stable-alpine
    container_name: alfasoft_web_prod
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
