version: "3.8"

services:
    app:
        build: .
        container_name: alfasoft_app_dev
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            APP_DEBUG: "true"
            APP_KEY: ${APP_KEY}
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: secret
        depends_on:
            - db

    db:
        image: mariadb:10.6
        container_name: alfasoft_db_dev
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306" # expõe porta para acesso externo
        volumes:
            - db_data_dev:/var/lib/mysql

    web:
        image: nginx:stable-alpine
        container_name: alfasoft_web_dev
        ports:
            - "8000:80"
        depends_on:
            - app
        volumes:
            - .:/var/www/html:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
    db_data_dev:
